# this Makefile is for old users, for new users, just go install in the 2 directories
install:
	go install ; cd ../bmgen && go install ; if [ -f /usr/local/bin/bmgen ]; then rm /usr/local/bin/bmgen; fi