package(default_visibility = ["//visibility:public"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_library",
)

go_library(
    name = "go_default_library",
    srcs = ["generator.go"],
    importpath = "go-common/app/tool/protoc-gen-bm/generator",
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
    deps = ["@com_github_golang_protobuf//protoc-gen-go/plugin:go_default_library"],
)

filegroup(
    name = "package-srcs",
    srcs = glob(["**"]),
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)

filegroup(
    name = "all-srcs",
    srcs = [":package-srcs"],
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
)
