// Code generated by entc, DO NOT EDIT.

package sensordata

const (
	// Label holds the string label denoting the sensordata type in the database.
	Label = "sensor_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldSensorID holds the string denoting the sensor_id field in the database.
	FieldSensorID = "sensor_id"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldCPU holds the string denoting the cpu field in the database.
	FieldCPU = "cpu"
	// Table holds the table name of the sensordata in the database.
	Table = "sensor_data"
)

// Columns holds all SQL columns for sensordata fields.
var Columns = []string{
	FieldID,
	FieldTime,
	FieldSensorID,
	FieldTemperature,
	FieldCPU,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
